package com.wrdelmanto.papps

const val ONE_SECOND_IN_MILLIS = 1000L
const val THREE_QUARTERS_SECOND_IN_MILLIS = 750L
const val HALF_SECOND_IN_MILLIS = 500L
const val ONE_QUARTER_SECOND_IN_MILLIS = 250L

