package com.wrdelmanto.papps.apps.random.randomQuote

// https://www.pensador.com/autores/

// List with all the authors from O Pensador website
val allAuthorsList: List<String> = listOf(
    "Albert Einstein",
    "Amyr Klink",
    "Antonie de Saint-Exupéry",
    "Aristóteles",
    "Augusto Cury",
    "Benjamin Franklin",
    "Carlos Drummond de Andrade",
    "Charles Chaplin",
    "Clarice Lispector",
    "Confúcio",
    "Cora Coralina",
    "Cynthia Kersey",
    "Dalai Lama",
    "Desconhecido",
    "D. Elhers",
    "Evelyn Beatrice Hall",
    "Fernando Pessoa",
    "Fernando Teixeira de Andrade",
    "Friedrich Nietzsche",
    "Garth Henrichs",
    "Georges Bernanos",
    "Geraldo Eustáquio de Souza",
    "Gloria Hurtado",
    "Haile Selassie",
    "Henry Ford",
    "John Dryden",
    "John Ruskin",
    "John Wooden",
    "Joseph Addison",
    "Khalil Gibran",
    "Leon Tolstói",
    "Leonardo da Vinci",
    "Lilian Tonet",
    "Luís de Camões",
    "Mahatma Gandhi",
    "Maria Julia Paes de Silva",
    "Mario Quintana",
    "Maurice Switzer",
    "Machado de Assis",
    "Martin Luther King",
    "Millôr Fernandes",
    "Myrtes Mathias",
    "Nemo Nox",
    "Oscar Wilde",
    "Oliver Goldsmith",
    "Oliver Wendell Holmes Sr.",
    "Oswaldo Montenegro",
    "Paulo Coelho",
    "Paulo Roberto Gaefke",
    "Pitágoras",
    "Platão",
    "Roberto Shinyashiki",
    "Roger Bussy-Rabutin",
    "Rui Barbosa",
    "Santo Agostinho",
    "Sarah Westphal",
    "Sêneca",
    "Sigmund Freud",
    "Sócrates",
    "Stubby Currence",
    "Thich Nhat Hanh",
    "Toquinho e Mutinho",
    "Victor Hugo",
    "Vinicius de Moraes",
    "Vladimir Maiakóviski",
    "Waldemar Valle Martins",
    "William James",
    "William Shakespeare"
)