package com.wrdelmanto.papps.utils

// Click counter
const val SP_CC_HIGH_SCORE = "SHARED_PREFERENCES_CLICK_COUNTER_HIGH_SCORE"

// Money converter
const val SP_MC_PRIMARY_CONVERSION = "SHARED_PREFERENCES_MONEY_CONVERTER_PRIMARY_CONVERSION"
const val SP_MC_SECONDARY_CONVERSION = "SHARED_PREFERENCES_MONEY_CONVERTER_SECONDARY_CONVERSION"

// Dice
const val SP_D_DICE_HISTORY = "SHARED_PREFERENCES_DICE_DICE_HISTORY"

// Random letter
const val SP_RL_LETTER_HISTORY = "SHARED_PREFERENCES_RANDOM_LETTER_LETTER_HISTORY"

// Random number
const val SP_RN_NUMBER_HISTORY = "SHARED_PREFERENCES_RANDOM_NUMBER_NUMBER_HISTORY"
const val SP_RN_MIN = "SHARED_PREFERENCES_RANDOM_NUMBER_MIN"
const val SP_RN_MAX = "SHARED_PREFERENCES_RANDOM_NUMBER_MAX"

// Tip
const val SP_T_TIP_SWITCH = "SHARED_PREFERENCES_TIP_TIP_SWITCH"
const val SP_T_TOTAL_SWITCH = "SHARED_PREFERENCES_TIP_TOTAL_SWITCH"
const val SP_T_TIP_PERCENTAGE = "SHARED_PREFERENCES_TIP_TIP_PERCENTAGE"

// Unscramble
const val SP_U_HIGH_SCORE = "SHARED_PREFERENCES_UNSCRAMBLE_HIGH_SCORE"
const val SP_U_CURRENT_WORD = "SHARED_PREFERENCES_UNSCRAMBLE_CURRENT_WORD"
const val SP_U_SCRAMBLED_WORD = "SHARED_PREFERENCES_UNSCRAMBLE_SCRAMBLED_WORD"

// Easter egg
const val SP_EASTER_EGG = "SHARED_PREFERENCES_EASTER_EGG"